<%@ page language="java" pageEncoding="UTF-8"%>

<link href="/resources/css/header.css" rel="stylesheet" type="text/css">
<link href="/resources/css/prod_detail.css" rel="stylesheet" type="text/css">
<link href="/resources/css/footer.css" rel="stylesheet" type="text/css">
<link href="/resources/css/banner.css" rel="stylesheet" type="text/css">
<link href="/resources/css/home.css" rel="stylesheet" type="text/css">
<link href="/resources/css/pageapp.css" rel="stylesheet" type="text/css">
<link href="/resources/css/06e50c5.css" rel="stylesheet" type="text/css">
<link href="/resources/css/0c0bd8f.css" rel="stylesheet" type="text/css">
<link href="/resources/css/0d0d927.css" rel="stylesheet" type="text/css">
<link href="/resources/css/174c879.css" rel="stylesheet" type="text/css">
<link href="/resources/css/1e20f03.css" rel="stylesheet" type="text/css">
<link href="/resources/css/235e2a9.css" rel="stylesheet" type="text/css">
<link href="/resources/css/24dfaf3.css" rel="stylesheet" type="text/css">
<link href="/resources/css/2bffad8.css" rel="stylesheet" type="text/css">
<link href="/resources/css/2ee49b5.css" rel="stylesheet" type="text/css">
<link href="/resources/css/30e2c3c.css" rel="stylesheet" type="text/css">
<link href="/resources/css/325de86.css" rel="stylesheet" type="text/css">
<link href="/resources/css/359f65d.css" rel="stylesheet" type="text/css">
<link href="/resources/css/382e739.css" rel="stylesheet" type="text/css">
<link href="/resources/css/3dec003.css" rel="stylesheet" type="text/css">
<link href="/resources/css/436339b.css" rel="stylesheet" type="text/css">
<link href="/resources/css/4688896.css" rel="stylesheet" type="text/css">
<link href="/resources/css/48656c7.css" rel="stylesheet" type="text/css">
<link href="/resources/css/4ad8835.css" rel="stylesheet" type="text/css">
<link href="/resources/css/4e7385d.css" rel="stylesheet" type="text/css">
<link href="/resources/css/60ed898.css" rel="stylesheet" type="text/css">
<link href="/resources/css/6c311e9.css" rel="stylesheet" type="text/css">
<link href="/resources/css/6dd67bf.css" rel="stylesheet" type="text/css">
<link href="/resources/css/734fa9a.css" rel="stylesheet" type="text/css">
<link href="/resources/css/7596802.css" rel="stylesheet" type="text/css">
<link href="/resources/css/7800e03.css" rel="stylesheet" type="text/css">
<link href="/resources/css/7af5c23.css" rel="stylesheet" type="text/css">
<link href="/resources/css/7f27f3c.css" rel="stylesheet" type="text/css">
<link href="/resources/css/80f1d1f.css" rel="stylesheet" type="text/css">
<link href="/resources/css/85f981f.css" rel="stylesheet" type="text/css">
<link href="/resources/css/91fc84c.css" rel="stylesheet" type="text/css">
<link href="/resources/css/9240ced.css" rel="stylesheet" type="text/css">
<link href="/resources/css/961cf95.css" rel="stylesheet" type="text/css">
<link href="/resources/css/97ccca4.css" rel="stylesheet" type="text/css">
<link href="/resources/css/9c84e6e.css" rel="stylesheet" type="text/css">
<link href="/resources/css/a52fa45.css" rel="stylesheet" type="text/css">
<link href="/resources/css/a57699c.css" rel="stylesheet" type="text/css">
<link href="/resources/css/ac866cc.css" rel="stylesheet" type="text/css">
<link href="/resources/css/app.css" rel="stylesheet" type="text/css">
<link href="/resources/css/c2874b8.css" rel="stylesheet" type="text/css">
<link href="/resources/css/c3e0280.css" rel="stylesheet" type="text/css">
<link href="/resources/css/cc256c4.css" rel="stylesheet" type="text/css">
<link href="/resources/css/cfe0307.css" rel="stylesheet" type="text/css">
<link href="/resources/css/e72cabe.css" rel="stylesheet" type="text/css">
<link href="/resources/css/ed8e821.css" rel="stylesheet" type="text/css">
<link href="/resources/css/used_prod_sell.css" rel="stylesheet" type="text/css">
<link href="/resources/css/review.css" rel="stylesheet" type="text/css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
<link href="/resources/css/acdef89.css" rel="stylesheet" type="text/css">
<link href="/resources/css/1fbb0fa.css" rel="stylesheet" type="text/css">
<link href="/resources/css/00c65a6.css" rel="stylesheet" type="text/css">